#!/usr/bin/env bash
# Install edittude-v3 and put it on PATH.
#
#   curl -LsSf https://raw.githubusercontent.com/SpectrumTantrum/edittude-v3/main/install.sh | bash
#
# From a checkout:
#
#   ./install.sh
#
# Optional environment:
#   EDITTUDE_REPO     git URL to clone when this script is not next to pyproject.toml
#   EDITTUDE_REF      branch or tag (default: main)
#   EDITTUDE_HOME     clone destination (default: ~/.local/share/edittude-v3)
#   EDITTUDE_BIN      launcher directory (default: ~/.local/bin)
#   EDITTUDE_PYTHON   Python version for uv (default: 3.13)

set -euo pipefail

REPO="${EDITTUDE_REPO:-https://github.com/SpectrumTantrum/edittude-v3.git}"
REF="${EDITTUDE_REF:-main}"
PREFIX="${EDITTUDE_HOME:-${HOME}/.local/share/edittude-v3}"
BIN_DIR="${EDITTUDE_BIN:-${HOME}/.local/bin}"
PYTHON_VERSION="${EDITTUDE_PYTHON:-3.13}"

bold=""
reset=""
red=""
green=""
dim=""
if [ -t 1 ]; then
  bold="$(printf '\033[1m')"
  reset="$(printf '\033[0m')"
  red="$(printf '\033[31m')"
  green="$(printf '\033[32m')"
  dim="$(printf '\033[2m')"
fi

log() { printf '%s\n' "$*"; }
info() { printf '%sinfo%s %s\n' "$dim" "$reset" "$*" >&2; }
ok() { printf '%sok%s   %s\n' "$green" "$reset" "$*" >&2; }
die() { printf '%serror%s %s\n' "$red" "$reset" "$*" >&2; exit 1; }

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    die "Missing $1. Install it and run this again."
  fi
}

script_dir() {
  local source="${BASH_SOURCE[0]:-}"
  if [ -z "$source" ] || [ ! -f "$source" ]; then
    return 1
  fi
  local dir
  dir="$(cd "$(dirname "$source")" && pwd)"
  if [ -f "${dir}/pyproject.toml" ] && grep -q 'name = "edittude-v3"' "${dir}/pyproject.toml"; then
    printf '%s\n' "$dir"
    return 0
  fi
  return 1
}

find_uv() {
  if command -v uv >/dev/null 2>&1; then
    command -v uv
    return 0
  fi
  if [ -x "${HOME}/.local/bin/uv" ]; then
    printf '%s\n' "${HOME}/.local/bin/uv"
    return 0
  fi
  return 1
}

install_uv() {
  local uv_bin
  if uv_bin="$(find_uv)"; then
    info "uv already installed ($uv_bin)"
    printf '%s\n' "$uv_bin"
    return 0
  fi
  info "Installing uv"
  if command -v curl >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- https://astral.sh/uv/install.sh | sh
  else
    die "Need curl or wget to install uv."
  fi
  if uv_bin="$(find_uv)"; then
    printf '%s\n' "$uv_bin"
    return 0
  fi
  die "uv installed but is not on PATH. Open a new shell or add ${HOME}/.local/bin to PATH."
}

resolve_prefix() {
  local checkout
  if checkout="$(script_dir)"; then
    printf '%s\n' "$checkout"
    return 0
  fi
  need_cmd git
  if [ -f "${PREFIX}/pyproject.toml" ] && grep -q 'name = "edittude-v3"' "${PREFIX}/pyproject.toml"; then
    if [ -d "${PREFIX}/.git" ]; then
      info "Updating ${PREFIX}"
      git -C "$PREFIX" fetch --depth 1 origin "$REF"
      git -C "$PREFIX" checkout --force -B "$REF" "FETCH_HEAD"
    else
      info "Using existing checkout ${PREFIX}"
    fi
    printf '%s\n' "$PREFIX"
    return 0
  fi
  if [ -e "$PREFIX" ] && [ ! -d "$PREFIX" ]; then
    die "${PREFIX} exists and is not a directory."
  fi
  if [ -d "$PREFIX" ] && [ -n "$(ls -A "$PREFIX" 2>/dev/null)" ]; then
    die "${PREFIX} exists and is not an edittude-v3 checkout. Set EDITTUDE_HOME to an empty directory."
  fi
  info "Cloning ${REPO} (${REF}) into ${PREFIX}"
  mkdir -p "$(dirname "$PREFIX")"
  if ! git clone --depth 1 --branch "$REF" "$REPO" "$PREFIX"; then
    die "Clone failed. Publish the repo, or run ./install.sh from a checkout. Override the URL with EDITTUDE_REPO."
  fi
  printf '%s\n' "$PREFIX"
}

write_launcher() {
  local name="$1"
  local target="${BIN_DIR}/${name}"
  mkdir -p "$BIN_DIR"
  cat >"$target" <<EOF
#!/bin/sh
# generated by edittude-v3/install.sh
set -e
export EDITTUDE_ROOT="${PREFIX}"
if command -v uv >/dev/null 2>&1; then
  UV="\$(command -v uv)"
elif [ -x "\${HOME}/.local/bin/uv" ]; then
  UV="\${HOME}/.local/bin/uv"
else
  echo "uv is missing. Re-run the edittude-v3 installer." >&2
  exit 1
fi
exec "\$UV" run --project "${PREFIX}" ${name} "\$@"
EOF
  chmod +x "$target"
}

path_contains() {
  case ":${PATH}:" in
    *":${1}:"*) return 0 ;;
    *) return 1 ;;
  esac
}

if [ "$(id -u)" -eq 0 ]; then
  die "Do not install edittude-v3 as root."
fi

log "${bold}edittude-v3${reset}"
PREFIX="$(resolve_prefix)"
UV_BIN="$(install_uv)"

info "Syncing Python ${PYTHON_VERSION} dependencies in ${PREFIX}"
"$UV_BIN" sync --python "$PYTHON_VERSION" --project "$PREFIX"

if [ ! -f "${PREFIX}/.env" ] && [ -f "${PREFIX}/.env.example" ]; then
  cp "${PREFIX}/.env.example" "${PREFIX}/.env"
  info "Wrote ${PREFIX}/.env (add DEEPSEEK_API_KEY)"
fi

write_launcher edittude-v3
write_launcher edittude-media
ok "Launchers in ${BIN_DIR}"

if ! command -v ffmpeg >/dev/null 2>&1 || ! command -v ffprobe >/dev/null 2>&1; then
  log "ffmpeg and ffprobe are not on PATH. Install them before you cut."
  if command -v brew >/dev/null 2>&1; then
    log "  brew install ffmpeg"
  else
    log "  https://ffmpeg.org/download.html"
  fi
fi

if ! path_contains "$BIN_DIR"; then
  log "Add this to your shell profile, then open a new terminal:"
  log "  export PATH=\"${BIN_DIR}:\$PATH\""
fi

ok "Installed."
log
log "Put a DeepSeek key in ${PREFIX}/.env"
log "  DEEPSEEK_API_KEY=sk-..."
log "Get a key from https://platform.deepseek.com"
log
log "Then:"
log "  edittude-v3"
log "  edittude-v3 ask \"make a cut from /path/to/footage\""
